<?php

namespace AppBundle\Repository;

use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    use ORMBehaviors\Timestampable\Timestampable;
}
