AppBundle\Entity\Product:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [ product ]
        name:
            expose: true
            groups: [ product ]
        sku:
            expose: true
            groups: [ product ]
        price:
            expose: true
            groups: [ product ]
        quantity:
            expose: true
            groups: [ product ]
        category:
            serialized_name: category_data
            expose: true
            groups: [ product ]
    virtual_properties:
        getCategoryName:
            serialized_name: category
            type: string