# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    appbundle.product.entity:
        class: AppBundle\Entity\Product

    appbundle.product.form_type:
        class: AppBundle\Form\ProductType

    appbundle.product.handler:
        class: AppBundle\Handler\ProductHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@appbundle.product.entity"
            - "@form.factory"
            - "@appbundle.product.form_type"
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
